---

- hosts: all
  gather_facts: no
  tasks:

    # Install Node v6
    - block:
        - apt_key:
            url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
            state: present
        - apt_repository:
            repo: "deb https://deb.nodesource.com/node_6.x trusty main"
            state: present
        - apt: name=nodejs state=present
      become: yes

    - name: Install elm
      npm: name=elm version=0.17 global=yes
      become: yes

    - name: Set en_US.UTF-8 locale
      locale_gen: name=en_US.UTF-8
      tags: bash

